app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(array('middleware'=>'auth'), function()
{
    Route::get('/', function () {
        return redirect(url('/news'));
    });

    /*
    +--------+-----------+------------------+--------------+---------------------------------------------+------------+
    | Domain | Method    | URI              | Name         | Action                                      | Middleware |
    +--------+-----------+------------------+--------------+---------------------------------------------+------------+
    |        | GET|HEAD  | /                |              | Closure                                     | web        |
    |        | POST      | news             | news.store   | App\Http\Controllers\NewsController@store   | web        |
    |        | GET|HEAD  | news             | news.index   | App\Http\Controllers\NewsController@index   | web        |
    |        | GET|HEAD  | news/create      | news.create  | App\Http\Controllers\NewsController@create  | web        |
    |        | DELETE    | news/{news}      | news.destroy | App\Http\Controllers\NewsController@destroy | web        |
    |        | PUT|PATCH | news/{news}      | news.update  | App\Http\Controllers\NewsController@update  | web        |
    |        | GET|HEAD  | news/{news}      | news.show    | App\Http\Controllers\NewsController@show    | web        |
    |        | GET|HEAD  | news/{news}/edit | news.edit    | App\Http\Controllers\NewsController@edit    | web        |
    +--------+-----------+------------------+--------------+---------------------------------------------+------------+
    */
    Route::resource('news', 'NewsController');
    Route::post('news/comment/{news}', ['as' => 'news.storeComment', 'uses' => 'NewsController@storeComment']);


    Route::resource('links', 'LinksController');
    Route::get('/maps/UserLocation/', ['as' => 'maps.getUserLocation', 'uses' => 'MapsController@getUserLocation']);
    Route::post('/maps/UserLocation/', ['as' => 'maps.postUserLocation', 'uses' =>'MapsController@postUserLocation']);
    Route::get('/maps/UsersLocation/', ['as' => 'maps.getLocations', 'uses' => 'MapsController@getLocations']);
    Route::resource('maps', 'MapsController');
});

Route::auth();

app/Link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $fillable = array('link', 'description', 'profile_id');

    public function profile()
    {
        return $this->belongsTo('App\UserProfile');
    }
}

app/Http/Controllers/LinksController.php
<?php

namespace App\Http\Controllers;

use App\Link;
use Illuminate\Http\Request;

use App\Http\Requests;

class LinksController extends Controller
{
    public function index()
    {
        $links = Link::all();
        return view('links.index', compact('links'));
    }

    public function create()
    {
        return view('links.create');
    }

    public function store(Request $request)
    {
        if(stripos($request->get('link'), 'http://') == FALSE AND stripos($request->get('link'), 'https://') == FALSE)
            $request->merge(array('link' => 'http://'.$request->get('link')));
        $request->merge(array('profile_id' => 1));
        Link::create($request->except('_token'));
        return redirect(route('links.index'));
    }

    public function edit($id)
    {
        $link = Link::findOrFail($id);
        return view('links.edit', compact('link'));
    }

    public function update($id, Request $request)
    {
        if(stripos($request->get('link'), 'http://') == FALSE AND stripos($request->get('link'), 'https://') == FALSE)
            $request->merge(array('link' => 'http://'.$request->get('link')));
        Link::find($id)->update($request->except('_token'));
        return redirect(route('links.index'));
    }

    public function destroy($id)
    {
        Link::destroy($id);
        return redirect(route('links.index'));
    }
}

resources/views/links/create.blade.php
@extends('tools.template.bootstrap-default')

@section('content')
    <div class="row">
        <div class="col-md-10">
            {{ Form::open(array('url' => route('links.store'))) }}
                <div class="form-group">
                    {{ Form::label('link', 'URL') }}
                    {{ Form::text('link', null, ['class' => 'form-control', 'placeholder' => 'Entrez votre lien']) }}
                </div>

                <div class="form-group">
                    {{ Form::label('description', 'Description') }}
                    {{ Form::text('description', null, ['class' => 'form-control', 'placeholder' => 'Entrez une description claire']) }}
                </div>

                <div class="form-group">
                    <button class="btn btn-primary">Ajoutez votre lien</button>
                </div>
            {{ Form::close() }}
        </div>
    </div>

@endsection

resources/views/links/edit.blade.php
@extends('tools.template.bootstrap-default')

@section('content')
    <div class="row">
        <div class="col-md-10">
            {{ Form::open(array('url' => route('links.update', $link), 'method' => 'put')) }}
                <div class="form-group">
                    {{ Form::label('link', 'URL') }}
                    {{ Form::text('link', $link->link, ['class' => 'form-control', 'placeholder' => 'Entrez votre lien']) }}
                </div>

                <div class="form-group">
                    {{ Form::label('description', 'Description') }}
                    {{ Form::text('description', $link->description, ['class' => 'form-control', 'placeholder' => 'Entrez une description claire']) }}
                </div>

                <div class="form-group">
                    <button class="btn btn-primary">Editez votre lien</button>
                </div>
            {{ Form::close() }}
        </div>
    </div>

@endsection

resources/views/links/index.blade.php
@extends('tools.template.bootstrap-default')

@section('content')
    <div class="row">
        <div class="col-md-4">
            <a href="{{ route('links.create') }}" class="btn btn-primary">Créer un nouveau lien</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10">
            <table class="table table-condensed">
                <tr>
                    <th>#</th>
                    <th>Proposé par</th>
                    <th>URL</th>
                    <th>Description</th>
                    <th>Options</th>
                </tr>
                @foreach($links as $link)
                    <tr>
                        <td>{{ $link->id }}</td>
                        <td>{{ $link->profile->fullName() }}</td>
                        <td><a href="{{ $link->link }}">{{ $link->link }}</a></td>
                        <td>{{ $link->description }}</td>
                        <td>
                            <div class="form-group">
                                <a href="{{ route('links.edit', $link) }}" class="btn btn-primary">Editer</a>
                                {{ Form::open(array('url' => route('links.destroy', $link), 'method' => 'Delete')) }}
                                    <button class="btn btn-danger">Supprimer</button>
                                {{ Form::close() }}
                                <button href="" class="btn btn-warning">Signaler</button>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
@endsection